name: Build and Sign Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # necesario para cosign + OIDC

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-nginx-helloworld:latest .

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/my-nginx-helloworld:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Sign Docker image with Cosign
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign ghcr.io/${{ github.repository }}/my-nginx-helloworld:latest

